name: Build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    
    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: dev-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}

    - name: Build
      run: |
        npm install
        npm run build
    
    - name: Deploy
      uses: docker://peaceiris/gh-pages:v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: nightly
        PUBLISH_DIR: ./build
      with:
        emptyCommits: false
